"""Markdown レポート生成モジュール"""

from datetime import datetime
from pathlib import Path
from zoneinfo import ZoneInfo

from aion.models import Article

JST = ZoneInfo("Asia/Tokyo")

CATEGORY_LABELS = {
    "business": "ビジネス",
    "tech": "開発・技術",
    "research": "研究論文",
}


def generate_report(articles: list[Article], date: datetime | None = None) -> str:
    """要約済み記事からMarkdownレポートを生成"""
    if date is None:
        date = datetime.now(JST)

    date_str = date.strftime("%Y年%m月%d日")

    lines = [
        f"# AION デイリーレポート - {date_str}",
        "",
        f"AI分野の最新ニュース・論文をお届けします。（{len(articles)}件）",
        "",
        "---",
        "",
    ]

    # カテゴリ別にグループ化
    by_category: dict[str, list[Article]] = {}
    for article in articles:
        cat = article.category
        if cat not in by_category:
            by_category[cat] = []
        by_category[cat].append(article)

    # カテゴリ順に出力
    for category in ["business", "tech", "research"]:
        if category not in by_category:
            continue

        label = CATEGORY_LABELS.get(category, category)
        lines.append(f"## {label}")
        lines.append("")

        for article in by_category[category]:
            lines.extend(format_article(article))
            lines.append("")

    # フッター
    lines.extend([
        "---",
        "",
        f"*Generated by AION at {datetime.now(JST).strftime('%Y-%m-%d %H:%M')}*",
    ])

    return "\n".join(lines)


def format_article(article: Article) -> list[str]:
    """1記事をMarkdown形式にフォーマット"""
    lines = []

    # タイトル（リンク付き）
    lines.append(f"### [{article.title}]({article.url})")
    lines.append("")

    # メタ情報
    pub_date = article.published.strftime("%Y-%m-%d") if article.published else "不明"
    lines.append(f"**{article.source}** | {pub_date}")
    lines.append("")

    # AI要約
    if article.ai_summary:
        lines.append(article.ai_summary)
        lines.append("")

    # Why it matters
    if article.why_it_matters:
        lines.append(f"> **Why it matters**: {article.why_it_matters}")
        lines.append("")

    return lines


def save_report(content: str, output_dir: Path | None = None) -> Path:
    """レポートをファイルに保存"""
    if output_dir is None:
        output_dir = Path(__file__).parent.parent.parent.parent / "outputs"

    output_dir.mkdir(parents=True, exist_ok=True)

    date_str = datetime.now(JST).strftime("%Y%m%d")
    filename = f"report_{date_str}.md"
    filepath = output_dir / filename

    with open(filepath, "w") as f:
        f.write(content)

    return filepath
